import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FirestoreProvider } from "./_components/FirestoreProvider";
import { FirebaseAuthProvider } from "./_components/FirebaseAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FirebaseAuthProvider>
        <FirestoreProvider>
          <body className={inter.className}>{children}</body>
        </FirestoreProvider>
      </FirebaseAuthProvider>
    </html>
  );
}
