services:
  bun:
    build:
      context: .
    volumes:
      - ../:/workspaces/nextjs-todo
    command:  sleep infinity
    environment:
      - TZ=Asia/Tokyo
      - FIRESTORE_EMULATOR_HOST=firestore:8080

  firestore:
    image: motomotomato/firestore-emulator
    ports:
      - 8080:8080
      - 4000:4000
      - 9099:9099
    volumes:
      - ../firestore:/firestore
    command: ["emulators:start", "--project", "nextjs-todo"]