name: On Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - "nextjs-todo/**"

jobs:
  lint:
    uses: ./.github/workflows/check-lint.yml
  test-medium:
    needs:
      - lint
    uses: ./.github/workflows/test-medium.yml
